"""update in product img

Revision ID: 133648170c59
Revises: bcce8e551e07
Create Date: 2026-02-03 12:09:29.862914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '133648170c59'
down_revision: Union[str, Sequence[str], None] = 'bcce8e551e07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_images', sa.Column('public_id', sa.String(length=255), nullable=True))
    op.drop_column('product_images', 'is_delete')
    op.drop_column('product_images', 'deleted_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_images', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('product_images', sa.Column('is_delete', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('product_images', 'public_id')
    # ### end Alembic commands ###
