"""update coupon_code  model

Revision ID: 4a829a9ca5fb
Revises: f284006904b7
Create Date: 2026-01-29 17:10:12.007279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a829a9ca5fb'
down_revision: Union[str, Sequence[str], None] = 'f284006904b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupon_codes', sa.Column('coupon_type', sa.String(length=20), nullable=True))
    op.add_column('coupon_codes', sa.Column('disc_value', sa.Integer(), nullable=True))
    op.add_column('coupon_codes', sa.Column('order_value', sa.Integer(), nullable=True))
    op.drop_column('coupon_codes', 'flat')
    op.drop_column('coupon_codes', 'percentile')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupon_codes', sa.Column('percentile', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('coupon_codes', sa.Column('flat', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('coupon_codes', 'order_value')
    op.drop_column('coupon_codes', 'disc_value')
    op.drop_column('coupon_codes', 'coupon_type')
    # ### end Alembic commands ###
