"""remove password from customer

Revision ID: 648a862bd238
Revises: 9871c16feca7
Create Date: 2026-01-28 12:02:43.938517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '648a862bd238'
down_revision: Union[str, Sequence[str], None] = '9871c16feca7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'password')
    op.drop_column('email_otp', 'is_expire')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_otp', sa.Column('is_expire', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
