"""update in otp model name

Revision ID: 917c2b228f13
Revises: ce1eae7426f7
Create Date: 2026-01-28 12:44:12.060119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '917c2b228f13'
down_revision: Union[str, Sequence[str], None] = 'ce1eae7426f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mobile_otp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('otp', sa.String(length=6), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mobile_otp_id'), 'mobile_otp', ['id'], unique=False)
    op.create_index(op.f('ix_mobile_otp_mobile'), 'mobile_otp', ['mobile'], unique=False)
    op.drop_index(op.f('ix_email_otp_id'), table_name='email_otp')
    op.drop_index(op.f('ix_email_otp_mobile'), table_name='email_otp')
    op.drop_table('email_otp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_otp',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('otp', sa.VARCHAR(length=6), autoincrement=False, nullable=False),
    sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('mobile', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('email_otp_pkey'))
    )
    op.create_index(op.f('ix_email_otp_mobile'), 'email_otp', ['mobile'], unique=False)
    op.create_index(op.f('ix_email_otp_id'), 'email_otp', ['id'], unique=False)
    op.drop_index(op.f('ix_mobile_otp_mobile'), table_name='mobile_otp')
    op.drop_index(op.f('ix_mobile_otp_id'), table_name='mobile_otp')
    op.drop_table('mobile_otp')
    # ### end Alembic commands ###
