"""create table menu,menu_items and more

Revision ID: aa9b5c2b93e7
Revises: 133648170c59
Create Date: 2026-02-03 13:07:10.837929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa9b5c2b93e7'
down_revision: Union[str, Sequence[str], None] = '133648170c59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uu_id', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('menu', sa.String(length=255), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('is_update', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menus_code'), 'menus', ['code'], unique=True)
    op.create_index(op.f('ix_menus_id'), 'menus', ['id'], unique=False)
    op.create_index(op.f('ix_menus_uu_id'), 'menus', ['uu_id'], unique=True)
    op.create_table('entity_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uu_id', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('main_category_id', sa.Integer(), nullable=True),
    sa.Column('entity_category', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('is_update', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['main_category_id'], ['main_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_categories_code'), 'entity_categories', ['code'], unique=True)
    op.create_index(op.f('ix_entity_categories_id'), 'entity_categories', ['id'], unique=False)
    op.create_index(op.f('ix_entity_categories_main_category_id'), 'entity_categories', ['main_category_id'], unique=False)
    op.create_index(op.f('ix_entity_categories_uu_id'), 'entity_categories', ['uu_id'], unique=True)
    op.create_table('menu_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uu_id', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=True),
    sa.Column('menu_category', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('is_update', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_categories_code'), 'menu_categories', ['code'], unique=True)
    op.create_index(op.f('ix_menu_categories_id'), 'menu_categories', ['id'], unique=False)
    op.create_index(op.f('ix_menu_categories_menu_id'), 'menu_categories', ['menu_id'], unique=False)
    op.create_index(op.f('ix_menu_categories_uu_id'), 'menu_categories', ['uu_id'], unique=True)
    op.create_table('menu_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uu_id', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=True),
    sa.Column('menu_category_id', sa.Integer(), nullable=True),
    sa.Column('item', sa.String(length=255), nullable=False),
    sa.Column('sale_price', sa.Float(), nullable=False),
    sa.Column('packing_charges', sa.Float(), nullable=True),
    sa.Column('max_order_quantity', sa.Integer(), nullable=True),
    sa.Column('cuisine_type', sa.String(length=100), nullable=True),
    sa.Column('item_image', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('item_status', sa.String(length=50), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('is_update', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['menu_category_id'], ['menu_categories.id'], ),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_items_code'), 'menu_items', ['code'], unique=True)
    op.create_index(op.f('ix_menu_items_id'), 'menu_items', ['id'], unique=False)
    op.create_index(op.f('ix_menu_items_menu_category_id'), 'menu_items', ['menu_category_id'], unique=False)
    op.create_index(op.f('ix_menu_items_menu_id'), 'menu_items', ['menu_id'], unique=False)
    op.create_index(op.f('ix_menu_items_uu_id'), 'menu_items', ['uu_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_menu_items_uu_id'), table_name='menu_items')
    op.drop_index(op.f('ix_menu_items_menu_id'), table_name='menu_items')
    op.drop_index(op.f('ix_menu_items_menu_category_id'), table_name='menu_items')
    op.drop_index(op.f('ix_menu_items_id'), table_name='menu_items')
    op.drop_index(op.f('ix_menu_items_code'), table_name='menu_items')
    op.drop_table('menu_items')
    op.drop_index(op.f('ix_menu_categories_uu_id'), table_name='menu_categories')
    op.drop_index(op.f('ix_menu_categories_menu_id'), table_name='menu_categories')
    op.drop_index(op.f('ix_menu_categories_id'), table_name='menu_categories')
    op.drop_index(op.f('ix_menu_categories_code'), table_name='menu_categories')
    op.drop_table('menu_categories')
    op.drop_index(op.f('ix_entity_categories_uu_id'), table_name='entity_categories')
    op.drop_index(op.f('ix_entity_categories_main_category_id'), table_name='entity_categories')
    op.drop_index(op.f('ix_entity_categories_id'), table_name='entity_categories')
    op.drop_index(op.f('ix_entity_categories_code'), table_name='entity_categories')
    op.drop_table('entity_categories')
    op.drop_index(op.f('ix_menus_uu_id'), table_name='menus')
    op.drop_index(op.f('ix_menus_id'), table_name='menus')
    op.drop_index(op.f('ix_menus_code'), table_name='menus')
    op.drop_table('menus')
    # ### end Alembic commands ###
