"""create site_cms model

Revision ID: b8ddd1616a22
Revises: 8dc68f76cf89
Create Date: 2026-02-07 17:07:36.145170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8ddd1616a22'
down_revision: Union[str, Sequence[str], None] = '8dc68f76cf89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_cms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_key', sa.String(length=50), nullable=False),
    sa.Column('meta_title', sa.String(length=255), nullable=True),
    sa.Column('subtitle', sa.String(length=255), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('page_content', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('is_update', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_cms_id'), 'site_cms', ['id'], unique=False)
    op.create_index(op.f('ix_site_cms_page_key'), 'site_cms', ['page_key'], unique=False)
    op.drop_index(op.f('product_name_trgm_idx'), table_name='products', postgresql_ops={'product_name': 'gin_trgm_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('product_name_trgm_idx'), 'products', ['product_name'], unique=False, postgresql_ops={'product_name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ix_site_cms_page_key'), table_name='site_cms')
    op.drop_index(op.f('ix_site_cms_id'), table_name='site_cms')
    op.drop_table('site_cms')
    # ### end Alembic commands ###
