"""create model for entity_categories,menus,menu_categories,menu_items

Revision ID: bcce8e551e07
Revises: cd52f91073b3
Create Date: 2026-02-03 11:43:31.007579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcce8e551e07'
down_revision: Union[str, Sequence[str], None] = 'cd52f91073b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
