"""update product_variants  model

Revision ID: cd52f91073b3
Revises: 4a829a9ca5fb
Create Date: 2026-01-31 12:19:24.924404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd52f91073b3'
down_revision: Union[str, Sequence[str], None] = '4a829a9ca5fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_variants', sa.Column('is_deliverable', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_variants', 'is_deliverable')
    # ### end Alembic commands ###
