"""update in otp model

Revision ID: ce1eae7426f7
Revises: 648a862bd238
Create Date: 2026-01-28 12:42:10.215659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce1eae7426f7'
down_revision: Union[str, Sequence[str], None] = '648a862bd238'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_otp', sa.Column('mobile', sa.String(length=20), nullable=False))
    op.drop_index(op.f('ix_email_otp_email'), table_name='email_otp')
    op.create_index(op.f('ix_email_otp_mobile'), 'email_otp', ['mobile'], unique=False)
    op.drop_column('email_otp', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_otp', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_email_otp_mobile'), table_name='email_otp')
    op.create_index(op.f('ix_email_otp_email'), 'email_otp', ['email'], unique=False)
    op.drop_column('email_otp', 'mobile')
    # ### end Alembic commands ###
