"""create coupon_code  model

Revision ID: ceee4070a1f5
Revises: c7f0d3b9c69b
Create Date: 2026-01-29 11:30:00.752742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ceee4070a1f5'
down_revision: Union[str, Sequence[str], None] = 'c7f0d3b9c69b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupon_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uu_id', sa.String(length=255), nullable=False),
    sa.Column('coupon_code', sa.String(length=100), nullable=False),
    sa.Column('flat', sa.Integer(), nullable=True),
    sa.Column('percentile', sa.Integer(), nullable=True),
    sa.Column('cap_limit', sa.Integer(), nullable=True),
    sa.Column('termscondition', sa.String(length=1000), nullable=True),
    sa.Column('coupon_description', sa.String(length=1000), nullable=True),
    sa.Column('use_limit', sa.Integer(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('is_update', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coupon_code')
    )
    op.create_index(op.f('ix_coupon_codes_id'), 'coupon_codes', ['id'], unique=False)
    op.create_index(op.f('ix_coupon_codes_uu_id'), 'coupon_codes', ['uu_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coupon_codes_uu_id'), table_name='coupon_codes')
    op.drop_index(op.f('ix_coupon_codes_id'), table_name='coupon_codes')
    op.drop_table('coupon_codes')
    # ### end Alembic commands ###
