"""create system_settings model

Revision ID: e265d4fa0c97
Revises: ffe1d2f7d56d
Create Date: 2026-02-09 13:38:42.934592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e265d4fa0c97'
down_revision: Union[str, Sequence[str], None] = 'ffe1d2f7d56d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
