"""change in product_variants model

Revision ID: ffe1d2f7d56d
Revises: b8ddd1616a22
Create Date: 2026-02-09 11:07:16.276566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffe1d2f7d56d'
down_revision: Union[str, Sequence[str], None] = 'b8ddd1616a22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_variants', sa.Column('quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_variants', 'quantity')
    # ### end Alembic commands ###
